### ISSUE TITLE
'Tomorrow' state not working

### ISSUE THREAD

**Issue by djiest** [bruxy70/Garbage-Collection#115]
After updating from 1.4.0 to  1.5.0 the state is shown correctly, until collection day is tomorrow/today, that is just show 'undefined'

![image](https://user-images.githubusercontent.com/1582516/76892977-d4e8f080-688b-11ea-91d5-f0db859e5ba2.png)

This is the code in my ui-lovelace.yaml
```   
 - type: custom:garbage-collection-card
          entity: sensor.date_pmd
          icon_size: 35px
          icon_color: green
          hide_date: false
          hide_before: 4
```

and this is my sensor template
```
  sensors:
    date_pmd:
      friendly_name: 'PMD'
      value_template: >-
        wordt {% if ((  as_timestamp(strptime(state_attr("sensor.afval_pmd","date"), "%Y-%m-%d")) 
          - as_timestamp(now()) ) / 86400 ) | round(0,"ceil") < 1 %}
          vandaag  
        {%- elif ((  as_timestamp(strptime(state_attr("sensor.afval_pmd","date"), "%Y-%m-%d")) 
          - as_timestamp(now()) ) / 86400 ) | round(0,"ceil") < 2 -%}
          morgen
        {%- else -%} over {{ ((  as_timestamp(strptime(state_attr("sensor.afval_pmd","date"), "%Y-%m-%d")) 
          - as_timestamp(now()) ) / 86400 ) | round(0,"ceil") }} 
          dagen 
        {%- endif %} geleegd.
      attribute_templates:
        next_date: >-
          {{ state_attr("sensor.afval_pmd","date") }}
        verbose_state: >-
          'true'
        days: >-
          {{ ((  as_timestamp(strptime(state_attr("sensor.afval_pmd","date"), "%Y-%m-%d")) - as_timestamp(now()) ) / 86400 ) | round(0,"ceil") }}

```

**Comment by bruxy70** [comment]
Please confirm the state of the sensor, in developper tool/states. Not the Lovelace card.
Any errors in the error log?
What is your configuration?

**Comment by djiest** [comment]
This is the state of the sensor
![image](https://user-images.githubusercontent.com/1582516/76893625-f72f3e00-688c-11ea-9265-958793b59a9d.png)

And there is an error in the logfile,

```
2020-03-17 19:45:32 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.date_pmd fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/template/sensor.py", line 224, in async_update
    self._state = self._template.async_render()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 222, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 440, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 814, in strptime
    return datetime.strptime(string, fmt)
TypeError: strptime() argument 1 must be str, not None

```

**Comment by bruxy70** [comment]
I guess this is a template sensor, a not garbage_collection sensor (even though it tries to imitate the garbage_sensor for some reason).
Also, the current version of garbage_collection is 2.17, there was never a version 1.5.0.
I am not sure if you have a problem with the template sensor or the garbage_collection card, but in either way, it looks like you are on a wrong site.

**Comment by djiest** [comment]
Right my bad. Sorry to trouble you, I appreciate your quick response!
