### ISSUE TITLE
Can't modify pickup day

### ISSUE THREAD

**Issue by bschatzow** [bruxy70/Garbage-Collection#135]
**Describe the bug**
A clear and concise description of what the bug is. Steps to reproduce.
After Integration is setup I can not modify the pickup day.
**Configuration**
YAML or Config Flow (GUI):

```
Copy the sensor configuration here (for config flow, describe parameters or add screenshots)
```

**Error log/debug information**
After I click on the Integration, then options, then submit I get: 
Unknown error occurred

```
Copy the error message from Developer tools/Logs here. 
Logger: aiohttp.server
Source: custom_components/garbage_collection/config_flow.py:500
First occurred: May 3, 2020, 1:05:31 PM (15 occurrences)
Last logged: 5:59:50 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 125, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 209, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 54, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 93, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 148, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 196, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/garbage_collection/config_flow.py", line 500, in async_step_init
    self._data.update(user_input)
AttributeError: 'mappingproxy' object has no attribute 'update'

```
To enable debug logging, add `custom_components.garbage_collection: debug` to your config under logger/logs.

**Screenshots**

**Version**
Integration version, Home Assistant version and configuration

**Comment by bruxy70** [comment]
Tested, it works for me. What is your garbage_collection version? What is your configuration?

**Comment by bschatzow** [comment]
How do I tell the version?  I am using home Assistant 109.3.  I have 4 integrations for garbage, nothing fancy. I setup one for each type of trash.

**Comment by bschatzow** [comment]
I must have installed manually and did not see the update.  2.2 fixes my issue.  Thanks.  Changed to a HACS install so I should see any future changes.
