### ISSUE TITLE
Error during setup with 0.111.0

### ISSUE THREAD

**Issue by SeraphimSerapis** [bruxy70/Garbage-Collection#170]
**Describe the bug**

The component seems to run into an issue when loading with the newly released 0.111.0 version.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

```yaml

```

**Error log/debug information**

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 190, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/garbage_collection/__init__.py", line 42, in async_setup
    CC_STARTUP_VERSION.format(name=DOMAIN, version=VERSION, issue_link=ISSUE_URL)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 55, in handle
    return_value = self.filter(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 751, in filter
    result = f.filter(record)
  File "/usr/src/homeassistant/homeassistant/components/logger/__init__.py", line 86, in filter
    return record.levelno >= self._logs[match.group(0)]
KeyError: 'custom_components.garbage_collection'
```

**Screenshots**

**Version**

Integration version: 3.0.1

Home Assistant version: 0.111.0

**Comment by SeraphimSerapis** [comment]
Thanks @bdraco - was there any change between 0.110 and 0.111 that causes this change in behavior? This line didn't cause any issues before.

**Comment by bdraco** [comment]
> Thanks @bdraco - was there any change between 0.110 and 0.111 that causes this change in behavior? This line didn't cause any issues before.

We changed the way we build the logger matching to fix some bugs and improve the performance in 0.111
