### ISSUE TITLE
Error with the Calendar integration

### ISSUE THREAD

**Issue by SeraphimSerapis** [bruxy70/Garbage-Collection#211]
**Describe the bug**

It seems like there is a bug that was introduced with the most recent update (`3.09`) running on `0.118.2` (see error message below). The sensors themselves seem to work fine -- this seems to be isolated to Home Assistant's Calendar.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? :  YAML

```yaml
garbage_collection:
  sensors:
    # Bio
    - name: "Garbage Biogut"
      frequency: "even-weeks"
      expire_after: '12:00'
      collection_days:
        - mon
      first_month: "may"
      last_month: "dec"
      exclude_dates:
        - '2020-12-21'
      include_dates:
        - '2020-12-19'
      verbose_state: true
      move_country_holidays: DE
      state: BE
      holiday_in_week_move: true
```

**Error log/debug information**

```txt
Logger: homeassistant.components.calendar
Source: components/calendar/__init__.py:61
Integration: Calendar (documentation, issues)
First occurred: 8:32:07 AM (2 occurrences)
Last logged: 8:32:07 AM

Error adding entities for domain calendar with platform garbage_collection
Error while setting up garbage_collection platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 161, in state
    event = normalize_event(event)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 72, in normalize_event
    start = get_date(start) if start is not None else None
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 61, in get_date
    dt.dt.datetime.combine(dt.parse_date(date["date"]), dt.dt.time.min)
TypeError: combine() argument 1 must be datetime.date, not None
```

**Screenshots**

**Version**

Integration version: 3.09

Home Assistant version: 0.118.2

**Comment by bruxy70** [comment]
That is weird. I copied your exact configuration and it works fine here (0.118.2). No errors. 
![image](https://user-images.githubusercontent.com/44951610/99948735-2aaa5c80-2d7a-11eb-91da-976c5bdc6810.png)

**Comment by bebach8** [comment]
I can confirm this error too. 

Integration version: 3.09
Home Assistant version: 0.118.3

Logger: homeassistant.components.calendar
Source: components/calendar/__init__.py:61
Integration: Calendar (documentation, issues)
First occurred: 6:42:44 PM (2 occurrences)
Last logged: 6:42:44 PM

    Error adding entities for domain calendar with platform garbage_collection
    Error while setting up garbage_collection platform for calendar

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities 
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 161, in state
    event = normalize_event(event)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 72, in normalize_event
    start = get_date(start) if start is not None else None
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 61, in get_date
    dt.dt.datetime.combine(dt.parse_date(date["date"]), dt.dt.time.min)
TypeError: combine() argument 1 must be datetime.date, not None

**Comment by bruxy70** [comment]
I temporaryily fixed that in 3.10. Plese test 3.11-beta, that should fix it  permanently, and show the expiry time correctly.

**Comment by bebach8** [comment]
3.11-beta appears to be working OK after first reboot. No errors in log with HA version 0.118.3. Data is showing in calendar panel as it is supposed to. Vaclav, thank you for taking care of that and educating us in your videos. Much appreciated.

**Comment by SeraphimSerapis** [comment]
I don't see an issue in 3.11-beta either. Seems to work so far!
