### ISSUE TITLE
24h time format unsupported

### ISSUE THREAD

**Issue by LazyEngineerToBe** [bruxy70/Garbage-Collection#273]
**Describe the bug**

The latest release of home assistant supports 24h time format. I'm using the `expire_after` argument and the sensor resets at 7 AM instead of 7 PM. I tried writing the time as `19:00` but it's not supported.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 
YAML

```yaml
garbage_collection:
  sensors:
    - name: Recycling
      hidden: true
      frequency: "weekly"
      collection_days: mon
      expire_after: 19:00
    - name: Waste
      hidden: true
      frequency: "weekly"
      collection_days: tue
      expire_after: 19:00
```

**Error log/debug information**

```txt
2021-06-08 10:02:35 ERROR (MainThread) [homeassistant.config] Unknown error calling garbage_collection CONFIG_SCHEMA
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config.py", line 808, in async_process_component_config
return component.CONFIG_SCHEMA(config) # type: ignore
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
cval = cvalue(key_path, value)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
return schema(data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
cval = cvalue(key_path, value)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 215, in _run
return self._exec(self._compiled, value, path)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 339, in _exec
v = func(path, v)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 635, in validate_sequence
cval = validate(index_path, value)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
return schema(data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
cval = cvalue(key_path, value)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
return schema(data)
File "/config/custom_components/garbage_collection/const.py", line 201, in time_text
return datetime.strptime(value, "%H:%M").time().strftime("%H:%M")
TypeError: strptime() argument 1 must be str, not int
2021-06-08 10:02:35 ERROR (MainThread) [homeassistant.setup] Setup failed for garbage_collection: Invalid config.
```

**Screenshots**

**Version**
Integration version: 
3.18
Home Assistant version: 
core-2021.6.3

**Comment by LazyEngineerToBe** [comment]
Nevermind, I just realized that the input should be a string.
