### ISSUE TITLE
[Bug] Group schedules broken since refactor

### ISSUE THREAD

**Issue by mdallaire** [bruxy70/Garbage-Collection#313]
**Describe the bug**

Since updating to the latest version my group entities are broken. I tried re-running the configuration for them and I get an error on the second prompt where I am to list the entities. If I just submit the existing values I get the error below.

**Configuration**

Config Flow
/config/.storage/core.config_entries 

Problem group:
```
            {
                "entry_id": "0ef51bb985f34d6780a6bd08d7a68526",
                "version": 1,
                "domain": "garbage_collection",
                "title": "Compost",
                "data": {
                    "unique_id": "08a6f6e2-fe44-41b6-a395-80d3fa900d9c",
                    "frequency": "group",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "verbose_format": "on {date}, in {days} days",
                    "date_format": "%d-%b-%Y",
                    "entities": [
                        "sensor.compost_ete",
                        "sensor.compost_hiver"
                    ]
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
            },
```
Devices member of the group (these are working correctly):
```            {
                "entry_id": "6a3b8351d57d483793f6931c296aad36",
                "version": 1,
                "domain": "garbage_collection",
                "title": "compost_ete",
                "data": {
                    "unique_id": "bc2711e1-af36-4d37-a8ed-2ebec9a7eb3f",
                    "frequency": "weekly",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "verbose_format": "on {date}, in {days} days",
                    "date_format": "%d-%b-%Y",
                    "collection_days": [
                        "wed"
                    ],
                    "first_month": "may",
                    "last_month": "sep",
                    "holiday_move_offset": 1,
                    "observed": true,
                    "holiday_in_week_move": false
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
            },
            {
                "entry_id": "1235fc1affa9442bbab9d0a93a96fdd1",
                "version": 1,
                "domain": "garbage_collection",
                "title": "compost_hiver",
                "data": {
                    "unique_id": "7cb35f2d-175c-40dd-8583-54dcc4e1fc2c",
                    "frequency": "every-n-weeks",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "verbose_format": "on {date}, in {days} days",
                    "date_format": "%d-%b-%Y",
                    "collection_days": [
                        "wed"
                    ],
                    "first_month": "oct",
                    "last_month": "apr",
                    "period": 2,
                    "first_week": 1,
                    "holiday_move_offset": 1,
                    "observed": false,
                    "holiday_in_week_move": false
                },
```

Error message in config GUI`s second prompt for the group

```User input malformed: expected str for dictionary value @ data['entities']```
List of entities (comma separated):
```sensor.compost_ete,sensor.compost_hiver```

**Error log/debug information**

```Update for sensor.bacs_compost fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/garbage_collection/sensor.py", line 726, in async_update
    await self._async_load_collection_dates()
  File "/config/custom_components/garbage_collection/sensor.py", line 682, in _async_load_collection_dates
    d = await self._async_find_next_date(d + timedelta(days=1))
  File "/config/custom_components/garbage_collection/sensor.py", line 641, in _async_find_next_date
    next_date = await self._async_find_candidate_date(day1) + relativedelta(
TypeError: unsupported operand type(s) for +: 'NoneType' and 'relativedelta'

```

**Screenshots**

**Version**

Integration version: 4.1

Home Assistant version: 2021.12.9

**Comment by bruxy70** [comment]
Can you check if 4.1.1 fixes that? Thanks!

**Comment by mdallaire** [comment]
Yep that fixed it, thank you!
