### ISSUE TITLE
error in HA log

### ISSUE THREAD

**Issue by Metlock11** [bruxy70/Garbage-Collection#320]
Logger: homeassistant.components.sensor
Source: custom_components/garbage_collection/sensor.py:157
Integration: Sensor (documentation, issues)
First occurred: 20:12:19 (1 occurrences)
Last logged: 20:12:19
Error while setting up garbage_collection platform for sensor

Traceback (most recent call last):
  File "/snap/home-assistant-snap/468/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/var/snap/home-assistant-snap/468/custom_components/garbage_collection/sensor.py", line 70, in async_setup_platform
    async_add_entities([GarbageCollection(hass, discovery_info)], True)
  File "/var/snap/home-assistant-snap/468/custom_components/garbage_collection/sensor.py", line 157, in __init__
    self._name = title if title is not None else config.get(CONF_NAME)
AttributeError: 'NoneType' object has no attribute 'get'

HA version actual and Garbage Colector too actual.
MW

**Comment by bruxy70** [comment]
I do not get such error, I cannot replicate that.
Not sure what is your configuration and what triggers that? Configuring new entity? Starting HA? Updating the sensor? Does the sensor work?
