### ISSUE TITLE
Blueprint 'Skip holiday' doesn't load

### ISSUE THREAD

**Issue by Sudo-Rob** [bruxy70/Garbage-Collection#325]
**Describe the bug**

Attempted to import 'Skip holiday' blueprint.  The 'Import Blueprint' dialog card appeared, but when 'Preview Blueprint' was selected, the URL field was empty (see figures).  Attempted 'bruxy70/skip_holiday', but it didn't resolve to a functional URL.  Seems the file is missing.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

Successfully migrated to GUI from YAML.  Apparently, no packages file needed to be generated.
Currently testing Blueprints.

```yaml

```
**Error log/debug information**

```txt
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://raw.githubusercontent.com/bruxy70/Garbage-Collection/development/blueprints/skip_holiday.yaml')
2022-01-30 14:28:49 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139915934981472] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/blueprint/websocket_api.py", line 68, in ws_import_blueprint
    imported_blueprint = await importer.fetch_blueprint_from_url(hass, msg["url"])
  File "/usr/src/homeassistant/homeassistant/components/blueprint/importer.py", line 225, in fetch_blueprint_from_url
    imported_bp = await func(hass, url)
  File "/usr/src/homeassistant/homeassistant/components/blueprint/importer.py", line 160, in fetch_blueprint_from_github_url
    resp = await session.get(import_url, raise_for_status=True)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 640, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://raw.githubusercontent.com/bruxy70/Garbage-Collection/development/blueprints/skip_holiday.yaml')
2022-01-30 14:28:51 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139915934981472] Error handling message: invalid url for dictionary value @ data['url']. Got 'bruxy70/include'
```

**Screenshots**

![image](https://user-images.githubusercontent.com/56487711/151714024-36f7b3e1-7ae3-47c6-82a4-90a7b65de397.png)

![image](https://user-images.githubusercontent.com/56487711/151714057-3f5515c1-2870-4dc3-adb6-bf3d2773f2d9.png)

**Version**

Integration version: 4.3

Home Assistant version: 

core-2021.12.10
supervisor-2021.12.2

**Comment by bruxy70** [comment]
Link in the readme fixed. Can you try? Thanks!

**Comment by Sudo-Rob** [comment]
👍

Yup.  That worked.  FYI, I haven't checked the bottom five yet...

Thanks so much for the fix (and the integration).
