### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not NoneType

### ISSUE THREAD

**Issue by eximo84** [bruxy70/Garbage-Collection#335]
**Describe the bug**

Updated to latest version yesterday, config move from configuration.yaml to UI.  Removed config in configuration.yaml and have the error below

**Configuration**

```json

```

**Error log/debug information**

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 512, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 716, in async_device_update
    raise exc
  File "/config/custom_components/garbage_collection/sensor.py", line 727, in async_update
    await self._async_load_collection_dates()
  File "/config/custom_components/garbage_collection/sensor.py", line 675, in _async_load_collection_dates
    await asyncio.wait_for(self.async_load_holidays(today), timeout=10)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/config/custom_components/garbage_collection/sensor.py", line 243, in async_load_holidays
    hol = holidays.CountryHoliday(self._country_holidays, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/holidays/utils.py", line 71, in CountryHoliday
    country_holiday = country(
  File "/usr/local/lib/python3.9/site-packages/holidays/countries/united_kingdom.py", line 36, in __init__
    HolidayBase.__init__(self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/holidays/holiday_base.py", line 182, in __init__
    self._populate(year)
  File "/usr/local/lib/python3.9/site-packages/holidays/countries/united_kingdom.py", line 109, in _populate
    self._country_specific(year)
  File "/usr/local/lib/python3.9/site-packages/holidays/countries/united_kingdom.py", line 160, in _country_specific
    if self.state not in ("Scotland") and year >= 1971:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

**Screenshots**

**Comment by bruxy70** [comment]
I do not know how you configured it, so I can't really troubleshoot it. Said that, the holidays functionality is obsolete. So I suggest you configure a new integration for Holidays, set-up an automation using a blueprint to deal with the holidays (and set the integration for manual update). 
The configuration for Holidays will be automatically removed in the upcoming release.

**Comment by bruxy70** [comment]
The upcoming release (currently in Beta) BTW implemented the Diagnostics feature, that will make it extremely easy to send the configuration with the ticket. Can't wait when this is out.

**Comment by bruxy70** [comment]
Please update to the new version and move the  Holiday config into blueprints. As this error comes from the Holidays configuration, that does not exist in the current version, I will close the issue. If you have some probem with the migration to Blueprints, let me know.
