### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by jcollas** [bruxy70/Garbage-Collection#43]
Upgraded to 2.4.

2019-11-23 07:53:31 ERROR (MainThread) [homeassistant.components.sensor] garbage_collection: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/garbage_collection/sensor.py", line 325, in async_update
    next_date = self.get_next_date(today)
  File "/config/custom_components/garbage_collection/sensor.py", line 297, in get_next_date
    filter(lambda date: date >= day1, self.__include_dates)
  File "/config/custom_components/garbage_collection/sensor.py", line 297, in <lambda>
    filter(lambda date: date >= day1, self.__include_dates)
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by bruxy70** [comment]
Right, looks like the timezone fix was not as smooth after all. 
I have uploaded [fixed version](https://github.com/bruxy70/Garbage-Collection/blob/development/custom_components/garbage_collection/sensor.py) to the development branch. Would you like to grab and test if it works? Thanks

**Comment by jcollas** [comment]
It's working again, thanks.  That was quick.
