### ISSUE TITLE
v2.6 of custom platform throws error

### ISSUE THREAD

**Issue by amaximus** [bruxy70/Garbage-Collection#48]
After installing garbage_collection platform via HACS (v2.6), restarting HA throws the error:

```
2019-11-29 14:26:54 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform garbage_collection
Traceback (most recent call last):
  File "/home/pi/ha_venv3_7/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/pi/homeassistant_conf/custom_components/garbage_collection/sensor.py", line 57, in async_setup_platform
    async_add_entities([GarbageCollection(hass, discovery_info)], True)
  File "/home/pi/homeassistant_conf/custom_components/garbage_collection/sensor.py", line 115, in __init__
    self.__name = config.get(CONF_NAME)
AttributeError: 'NoneType' object has no attribute 'get'
```

Thus, related sensors are not available anymore.
Earlier versions worked fine.
HA version is 0.102.2.

**Comment by bruxy70** [comment]
Can you please check, if you have configured the name? It is a required parameter.

**Comment by amaximus** [comment]
Yeah, I have the name:

```
(ha_venv3_7) pi@raspberrypi:~/homeassistant_conf/sensors $ ls -l b3_*
-rw-r--r-- 1 pi pi 248 Nov 12 19:42 b3_selective.yaml
-rw-r--r-- 1 pi pi  88 Nov 12 19:40 b3_waste.yaml
(ha_venv3_7) pi@raspberrypi:~/homeassistant_conf/sensors $ grep name b3_*
b3_selective.yaml:name: "Selective waste" # Every 4 weeks on Tuesday, starting on 4th week each year
b3_waste.yaml:name: Garbage
(ha_venv3_7) pi@raspberrypi:~/homeassistant_conf/sensors $

```

**Comment by bruxy70** [comment]
It does look like a problem with the configuration though. From what version did you update? There was a breaking change few months back as I was adding the config-flow. Can you check the config example in the readme and confirm that it is fine?

**Comment by amaximus** [comment]
thanks for the heads-up. That did the trick. My bad.
Anyway, now I moved to tracking the component with HACS, so hopefully  won't miss futher important changes.
Thanks for your support.
