### ISSUE TITLE
Latest version breaks entities with holiday shift enabled

### ISSUE THREAD

**Issue by cjramseyer** [bruxy70/Garbage-Collection#90]
**Describe the bug**
Upgrading to v2.14 both of the entities that I had the holiday shift enabled, ceased to exist

**Configuration**
Config Flow (GUI):

```
Copy the sensor configuration here (for config flow, describe parameters or add screenshots)
Entity: Garbage Weekly on Wednesday with holiday shift for US enable prior to upgrade.

**Error log/debug information**
No error displayed in the log, the entity ceased to exist until I reverted back to c2.12

**Version**
HA v0.102.3 Garbage Collection (attempted v2.14 works with v2.12)

**Comment by bruxy70** [comment]
I have downgraded to 2.12, configured the sensor for weekly on Wednesday with US holidays, then upgraded to 2.14 and it works fine. No idea why that would be.
It is weird, that you do not see anything in the logs, even the debug info. Can you please check that you have enabled the debugging (added `custom_components.garbage_collection: debug` under logs in the logger), and that you are looking in the Logs/Full Home Assistant Log?
I added one more debugging step that shows the parameters added in 2.14 (that should fall back to their defaults for sensors configured earlier), in version 2.15-beta. Can you please go to HACS, garbage collection, enable to show beta, upgrade to 2.15-beta, restart Home Assistant and check the logs again (full logs)? Thanks!

**Comment by johnkiddjr** [comment]
I observed a similar issue, though from a new setup perspective. Adding the sensor with holiday shift enabled results in the following error output:

```
Error while setting up platform garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/garbage_collection/sensor.py", line 69, in async_setup_entry
    async_add_devices([GarbageCollection(hass, config_entry.data)], True)
  File "/config/custom_components/garbage_collection/sensor.py", line 156, in __init__
    country_holidays, years=years, observed=observed
TypeError: CountryHoliday() got an unexpected keyword argument 'observed'
```

Rolled back to 2.12 and setup the component in the same way and there were no issues.

**Comment by bruxy70** [comment]
Thanks. Can you please try 2.15-beta2. And possibly enable debuging and send me the logs.
(Turn on show beta updates on HACS)

**Comment by johnkiddjr** [comment]
Updated to 2.15-beta2 and get this once Home Assistant restarted in the log:

```
Error while setting up platform garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/garbage_collection/sensor.py", line 69, in async_setup_entry
    async_add_devices([GarbageCollection(hass, config_entry.data)], True)
  File "/config/custom_components/garbage_collection/sensor.py", line 169, in __init__
    **kwargs
TypeError: CountryHoliday() got an unexpected keyword argument 'observed'
```

Enabled Debugging on the logger, restarted, and this is what is shown for this component in the log:

```
2020-01-27 12:52:55 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Trash) Country Holidays with parameters: prov: None, state: None, observed: True
2020-01-27 12:52:55 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Recycling) Country Holidays with parameters: prov: None, state: None, observed: True
2020-01-27 12:52:55 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/garbage_collection/sensor.py", line 69, in async_setup_entry
    async_add_devices([GarbageCollection(hass, config_entry.data)], True)
  File "/config/custom_components/garbage_collection/sensor.py", line 169, in __init__
    **kwargs
TypeError: CountryHoliday() got an unexpected keyword argument 'observed'
2020-01-27 12:52:55 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform garbage_collection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/garbage_collection/sensor.py", line 69, in async_setup_entry
    async_add_devices([GarbageCollection(hass, config_entry.data)], True)
  File "/config/custom_components/garbage_collection/sensor.py", line 169, in __init__
    **kwargs
TypeError: CountryHoliday() got an unexpected keyword argument 'observed'
```

**Comment by bruxy70** [comment]
Ok, that actually helped, but I still can't replicate it. Anyhow, I have added minimal version of the holiday library in the depencencies - beta3. Can you please try once more? Thanks!

**Comment by johnkiddjr** [comment]
With that update the components came back and work again.

This was the debug output in my log, which appears to indicate success in finding the holidays:

```
2020-01-27 15:47:26 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Trash) Country Holidays with parameters: country: US, prov: None, state: None, observed: True
2020-01-27 15:47:26 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Trash) Found these holidays: 
  2020-02-17: Washington's Birthday
  2020-05-25: Memorial Day
  2020-07-04: Independence Day
  2020-07-03: Independence Day (Observed)
  2020-09-07: Labor Day
  2020-10-12: Columbus Day
  2020-11-11: Veterans Day
  2020-11-26: Thanksgiving
  2020-12-25: Christmas Day
  2021-01-01: New Year's Day
  2021-12-31: New Year's Day (Observed)
  2021-01-18: Martin Luther King, Jr. Day
  2021-02-15: Washington's Birthday
  2021-05-31: Memorial Day
  2021-07-04: Independence Day
  2021-07-05: Independence Day (Observed)
  2021-09-06: Labor Day
  2021-10-11: Columbus Day
  2021-11-11: Veterans Day
  2021-11-25: Thanksgiving
  2021-12-25: Christmas Day
  2021-12-24: Christmas Day (Observed)
2020-01-27 15:47:26 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Recycling) Country Holidays with parameters: country: US, prov: None, state: None, observed: True
2020-01-27 15:47:26 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Recycling) Found these holidays: 
  2020-02-17: Washington's Birthday
  2020-05-25: Memorial Day
  2020-07-04: Independence Day
  2020-07-03: Independence Day (Observed)
  2020-09-07: Labor Day
  2020-10-12: Columbus Day
  2020-11-11: Veterans Day
  2020-11-26: Thanksgiving
  2020-12-25: Christmas Day
  2021-01-01: New Year's Day
  2021-12-31: New Year's Day (Observed)
  2021-01-18: Martin Luther King, Jr. Day
  2021-02-15: Washington's Birthday
  2021-05-31: Memorial Day
  2021-07-04: Independence Day
  2021-07-05: Independence Day (Observed)
  2021-09-06: Labor Day
  2021-10-11: Columbus Day
  2021-11-11: Veterans Day
  2021-11-25: Thanksgiving
  2021-12-25: Christmas Day
  2021-12-24: Christmas Day (Observed)
2020-01-27 15:47:26 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Trash) Calling update
2020-01-27 15:47:26 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Trash) Found next date: Jan-29-2020, that is in 2 days
2020-01-27 15:47:26 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Recycling) Calling update
2020-01-27 15:47:26 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (Recycling) Found next date: Jan-29-2020, that is in 2 days
```

**Comment by bruxy70** [comment]
Excellent, thanks @johnkiddjr . I will release it then. 
@cjramseyer , if that solves your problem as well, please close the issue.
